name: jellytics
description: A Jellyfin monitoring tool

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  dio: ^4.0.6                       # async http requests
  flutter_native_splash: ^2.2.9     # Loadup splash screen
  riverpod_annotation: ^1.0.4       # State management (riverpod)
  flutter_riverpod: ^2.1.1          # State management
  flutter_secure_storage: ^6.0.0    # For secure storage
  transparent_image: ^2.0.0         # Transparent images
  go_router: ^6.0.3                 # Routing
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0   # Launch icons
  flutter_lints: ^2.0.0             # See the `analysis_options.yaml` file for more information
  freezed: ^2.2.1                   # For data classes (freezed)
  build_runner: ^2.3.2              # For data classes (freezed)
  riverpod_generator: ^1.0.4        # State management (riverpod)

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon_jellyfish.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
